
language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t dimejitaiwo331/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true dimejitaiwo331/react-test npm test -- --coverage
after_success:
  - docker build -t dimejitaiwo331/complex-client ./client
  - docker build -t dimejitaiwo331/complex-nginx ./nginx
  - docker build -t dimejitaiwo331/complex-server ./server
  - docker build -t dimejitaiwo331/complex-worker ./worker