
language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t dimtaiwo331/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true dimtaiwo331/react-test npm test -- --coverage
after_success:
  - docker build -t dimtaiwo331/complex-nginx ./nginx
  - docker build -t dimtaiwo331/complex-server ./server
  - docker build -t dimtaiwo331/complex-worker ./worker
  - docker build -t dimtaiwo331/complex-client ./client
#login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#take those images and push them to docker hub
  - docker push dimtaiwo331/multi-client
  - docker push dimtaiwo331/complex-nginx
  - docker push dimtaiwo331/complex-server
  - docker push dimtaiwo331/complex-worker
  - docker push dimtaiwo331/complex-client
